name: fake_store
description: "Fake Store - An ecommerce application using FakeStore API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.1.0
  injectable: ^2.5.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  injectable_generator: ^2.8.0
  json_serializable: ^6.10.0
  bloc_test: ^10.0.0
  mockito: ^5.4.4
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
